# Node.js with Angular
# Build a Node.js project that uses Angular.
# Add steps that analyze code, save build artifacts, deploy, and more:
# https://docs.microsoft.com/azure/devops/pipelines/languages/javascript

variables:
  project: 'src/A-SIA2FrontendAngular'

trigger:
  branches:
    include:
    - develop
  paths:
    include:
    - src/A-SIA2FrontendAngular
pool:
  vmImage: ubuntu-20.04

steps:
- task: NodeTool@0
  inputs:
    versionSpec: '16.x'
  displayName: 'Install Node.js'

- script: |
    cd $(project)
    npm install -g @angular/cli
    npm install
  displayName: 'npm install'

- script: |
    cd $(project)
    ng build
  displayName: 'ng build'
- task: ArchiveFiles@2
  displayName: 'Archive files'
  inputs:
    rootFolderOrFile: '$(project)/dist/a-sia/'
    includeRootFolder: false
    archiveType: zip
    archiveFile: '$(Build.ArtifactStagingDirectory)/asia_angular-$(Build.BuildId).zip'
    replaceExistingArchive: true
- task: CopyFilesOverSSH@0
  inputs:
    sshEndpoint: 'miduskanich.com VPS'
    sourceFolder: '$(Build.ArtifactStagingDirectory)'
    contents: '**'
    targetFolder: '/var/www/a-sia'
    readyTimeout: '20000' 
    cleanTargetFolder: true
    overwrite: true
- task: SSH@0
  inputs:
    sshEndpoint: 'miduskanich.com VPS'
    runOptions: 'commands'
    commands: |
      unzip /var/www/a-sia/asia_angular-$(Build.BuildId).zip -d /var/www/a-sia
      rm /var/www/a-sia/asia_angular-$(Build.BuildId).zip
    readyTimeout: '20000'
